// Generated by CoffeeScript 1.10.0
var LifxClient, client, delay, lm, stateCheck;

LifxClient = require('node-lifx').Client;

lm = require('./lightmonitor');

client = new LifxClient();

client.on('light-new', function(light) {
  console.log("New " + light.id);
  return stateCheck("off-on");
});

client.on('light-offline', function(light) {
  return console.log("Lost " + light.id);
});

client.on('light-online', function(light) {
  console.log("Back " + light.id);
  return stateCheck("off-on");
});

delay = function(sec, func) {
  return setInterval(func, sec * 1000);
};

stateCheck = function(state) {
  var bedroom;
  bedroom = client.light("d073d512170d");
  if (lm.isLate()) {
    if (bedroom) {
      return bedroom.color(0, 0, 15, 2500, 1000, function() {
        return bedroom.off(10 * 60 * 1000);
      });
    }
  } else {
    if (bedroom) {
      return bedroom.getPower(function(err, powered) {
        if (powered) {
          return bedroom.color(0, 0, 85, 6500);
        }
      });
    }
  }
};

delay(60, function() {
  return stateCheck();
});

client.init();
