// Generated by CoffeeScript 1.10.0
var LightMonitor, moment;

moment = require('moment');

Number.prototype.mapFloat = function(in_min, in_max, out_min, out_max) {
  if (this < in_min) {
    return out_min;
  }
  if (this > in_max) {
    return out_max;
  }
  return parseFloat((this - in_min) * (out_max - out_min) / (in_max - in_min) + out_min);
};

LightMonitor = {
  isLate: function() {
    return moment().hours() >= 22 || moment().hours() <= 8;
  },
  getBrightness: function() {
    return moment.duration({
      hours: moment().hours(),
      minutes: moment().minutes()
    }).asHours();
  },
  getBrightnessForRange: function(hours, start, end) {
    var angle, f;
    angle = hours.mapFloat(start, end, 0, 180);
    f = Math.abs(Math.cos(angle * (Math.PI / 180)));
    return +f.toFixed(2);
  }
};

module.exports = LightMonitor;
